{
 "title": "HAproxy Servers | HAproxy",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "alias",
    "label": "Load Balancer",
    "query": "label_values(haproxy_up, instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(haproxy_server_bytes_in_total{instance=\"$alias\"}, namespace)"
   },
   {
    "name": "route",
    "label": "route",
    "query": "label_values(haproxy_server_bytes_in_total{instance=\"$alias\", namespace=~\"$namespace\"}, route)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_http_responses_total{instance=\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}, pod)"
   },
   {
    "name": "code",
    "label": "Http_code",
    "query": "label_values(haproxy_server_http_responses_total{instance=\"$alias\", namespace=~\"$namespace\", route=~\"$route\",pod=~\"$server\"}, code)"
   }
  ]
 },
 "panels": [
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_http_responses_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ namespace }}/{{ route }}/{{ pod }}/{{code}}"
    }
   ]
  },
  {
   "title": "Check Duration (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(haproxy_server_check_duration_milliseconds{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}) without (instance)",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Check Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_check_failures_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Downtime (s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_downtime_seconds_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ route }}/{{ pod}}"
    }
   ]
  },
  {
   "title": "Redispatch Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_redispatch_warnings_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_response_errors_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{namespace}}/{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Retry Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_retry_warnings_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_in_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_bytes_out_total{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "New Connections Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connections_total{backend=~\"$backend\", server=~\"$server\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_server_connection_errors_total{backend=~\"$backend\", server=~\"$server\", instance=\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}/{{ server }}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Current Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_queue{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Max Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_queue{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_sessions{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Servers UP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_up{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  },
  {
   "title": "Servers Weights",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_weight{namespace=~\"$namespace\",route=~\"$route\",server=~\"$server\", code=~\"$code\", instance=\"$alias\"}",
     "legendFormat": "{{ route }}/{{ pod }}"
    }
   ]
  }
 ]
}