{
 "title": "HAproxy Backend | HAproxy",
 "tags": [
  "haproxy",
  "backend"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "alias",
    "label": "Load Balancer",
    "query": "label_values(haproxy_up, instance)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_bytes_in_total{instance=~\"$alias\"}, backend)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(haproxy_backend_bytes_in_total{instance=~\"$alias\", backend=~\"$backend\"}, namespace)"
   },
   {
    "name": "route",
    "label": "route",
    "query": "label_values(haproxy_backend_bytes_in_total{instance=~\"$alias\", backend=~\"$backend\",namespace=~\"$namespace\"}, route)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_backend_http_responses_total{instance=~\"$alias\", backend=~\"$backend\", namespace=~\"$namespace\"}, code)"
   }
  ]
 },
 "panels": [
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ backend }}/{{route}}/{{ code }}"
    }
   ]
  },
  {
   "title": "Redispach Warnings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\", alias=~\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_response_errors_total{backend=~\"$backend\", instance=~\"$alias\",namespace=~\"$namespace\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Retry Wranings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_retry_warnings_total{backend=~\"$backend\", instance=~\"$alias\"}[$interval])",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_in_total{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_out_total{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "New Connections Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_connections_total{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_connection_errors_total{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Current Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Max Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_queue{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_session_rate{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_sessions{backend=~\"$backend\", instance=~\"$alias\", namespace=~\"$namespace\", route=~\"$route\"}",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\", instance=~\"$alias\",namespace=~\"$namespace\", route=~\"$route\"}",
     "legendFormat": "{{namespace}}/{{ route }}"
    }
   ]
  }
 ]
}