{
 "title": "Kubernetes Control Plane Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / sum(up{job=\"kubernetes-apiservers\"})) * 100"
    }
   ]
  },
  {
   "title": "Controller Managers UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-controllers\"} == 1) / sum(up{job=\"kubernetes-controllers\"})) * 100"
    }
   ]
  },
  {
   "title": "Nodes ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})/sum (kube_node_info)) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100"
    }
   ]
  },
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (rate(apiserver_request_count{code!~\"2..\"}[2m]))",
     "legendFormat": "Error Rate"
    },
    {
     "expr": "sum by(instance) (rate(apiserver_request_count[2m]))",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "API Server Request Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(apiserver_request_latencies_bucket{verb!~\"^(?:WATCH|WATCHLIST|PROXY|CONNECT)$\"}[5m])) \nby (le, resource, subresource, verb) ) / 1e+06"
    }
   ]
  },
  {
   "title": "End to End Scheduling Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)\n      BY (le, cluster)) / 1e+06",
     "legendFormat": "90percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)\n      BY (le, cluster)) / 1e+06",
     "legendFormat": "50percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)\n      BY (le, cluster)) / 1e+06",
     "legendFormat": "99percentile"
    }
   ]
  },
  {
   "title": "API Server Request Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(resource) (rate(apiserver_request_count{code!~\"2..\"}[2m]))",
     "legendFormat": "{{ resource }} - error-rate"
    },
    {
     "expr": "sum by(resource) (rate(apiserver_request_count[2m]))",
     "legendFormat": "{{ resource }} - req-rate"
    }
   ]
  },
  {
   "title": "kubelet_pleg_relist",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds { quantile=\"0.99\",job=\"kubernetes-cadvisor\" } ",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total[2m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0)",
     "legendFormat": "{{pod}}-restarting"
    },
    {}
   ]
  },
  {
   "title": "Kubelet Pod Start Latency",
   "type": "graph",
   "description": "Latency in microseconds for a single pod to go from pending to running. Broken down by podname.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_pod_start_latency_microseconds_sum[5m]) / rate(kubelet_pod_start_latency_microseconds_count[5m])",
     "legendFormat": "kubelet - {{instance}}"
    }
   ]
  }
 ]
}