{
 "title": "Pod resource usage req/lim",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_limitrange,namespace)"
   },
   {
    "name": "podname",
    "label": "podname",
    "query": "label_values(container_memory_rss{namespace=~\"$namespace\"},pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Memory usage against limits",
   "type": "graph",
   "description": "Will display the pod Memory usage and how it compares to the Pod limit and the Namespace limit",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace =~\"^$namespace*\", pod_name=~\"^$podname.*\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}-memused"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace =~\"^$namespace*\", pod=~\"^$podname.*\"}",
     "legendFormat": "{{ pod }}-memlimit"
    },
    {
     "expr": "kube_limitrange{namespace =~ '^$namespace.*', resource='memory',type='Pod',constraint='max'}",
     "legendFormat": "namespace-{{ namespace }}-memlimit"
    }
   ]
  },
  {
   "title": "Pod CPU usage against limits",
   "type": "graph",
   "description": "Will display the pod Memory usage and how it compares to the Pod limit and the Namespace limit",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace =~\"^$namespace*\", pod=~\"^$podname.*\"}",
     "legendFormat": "{{ pod }}-memlimit"
    },
    {
     "expr": "kube_limitrange{namespace =~ '^$namespace.*', resource='cpu',type='Pod',constraint='max'}",
     "legendFormat": "namespace-{{ namespace }}-memlimit"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{container_name=~\".+\",namespace=~\"^$namespace.*\",pod_name=~\"^$podname.*\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}-usage"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace =~\"^$namespace*\", pod_name=~\"^$podname.*\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}-received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace =~\"^$namespace*\", pod_name=~\"^$podname.*\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}-transferred"
    }
   ]
  }
 ]
}