{
 "title": "Project Resource reg/usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image=~\".+\"}[2m])) / scalar(sum(machine_cpu_cores { node_role_kubernetes_io_compute=\"true\"})) * 100"
    }
   ]
  },
  {
   "title": "Used CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image=~\".+\"}[2m]))"
    }
   ]
  },
  {
   "title": "Namespace Cpu  Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (sum(kube_pod_container_resource_requests_cpu_cores{namespace!~\"^openshift.*\", namespace=~\".+\"}) by (pod,namespace) * on (pod) group_left( kubernetes_namespace )  sum by (pod)(kube_pod_status_phase{phase=~\"Running|Pending\"})) / scalar(sum(machine_cpu_cores{ node_role_kubernetes_io_compute=\"true\"})) * 100"
    }
   ]
  },
  {
   "title": "Namespace Cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"\", namespace!~\"^openshift.*\", namespace=~\".+\"}[2m]) * 100) by (namespace) / scalar(sum(machine_cpu_cores{ node_role_kubernetes_io_compute=\"true\"})) "
    }
   ]
  },
  {
   "title": "Requested CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (sum(kube_pod_container_resource_requests_cpu_cores{namespace!~\"^openshift.*\", namespace=~\".+\"}) by (pod,namespace) * on (pod) group_left( kubernetes_namespace )  sum by (pod)(kube_pod_status_phase{phase=~\"Running|Pending\"}))"
    }
   ]
  },
  {
   "title": "CPU Request (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests_cpu_cores{namespace!~\"^openshift.*\", namespace=~\".+\"}) by (pod,namespace) * on (pod) group_left( kubernetes_namespace )  sum by (pod)(kube_pod_status_phase{phase=~\"Running|Pending\"})) / scalar(sum(machine_cpu_cores{ node_role_kubernetes_io_compute=\"true\"})) * 100"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "scalar(sum(machine_cpu_cores { node_role_kubernetes_io_compute=\"true\"}))"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_rss{namespace!~\"^openshift.*\",namespace=~\".+\"}) / (1024*1024*1024)",
     "legendFormat": "Gib"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 8 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum ( container_memory_rss{namespace!~\"^openshift.*\",namespace=~\".+\"}) / scalar(sum(machine_memory_bytes { node_role_kubernetes_io_compute=\"true\"})) * 100"
    }
   ]
  },
  {
   "title": "Namespace memory request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (sum(kube_pod_container_resource_requests_memory_bytes{namespace!~\"^openshift.*\", namespace=~\".+\"}) by (pod,namespace) * on (pod) group_left( kubernetes_namespace )  sum by (pod)(kube_pod_status_phase{phase=~\"Running|Pending\"}))  / scalar(sum(machine_memory_bytes { node_role_kubernetes_io_compute=\"true\"})) * 100"
    }
   ]
  },
  {
   "title": "Namespace memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum ( container_memory_rss{namespace!~\"^openshift.*\",namespace=~\".+\"}) by (namespace) / scalar(sum(machine_memory_bytes { node_role_kubernetes_io_compute=\"true\"})) * 100"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (sum(kube_pod_container_resource_requests_memory_bytes{namespace!~\"^openshift.*\", namespace=~\".+\"}) by (pod,namespace) * on (pod) group_left( kubernetes_namespace )  sum by (pod)(kube_pod_status_phase{phase=~\"Running|Pending\"}))  / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Memory Request(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (sum(kube_pod_container_resource_requests_memory_bytes{namespace!~\"^openshift.*\", namespace=~\".+\"}) by (pod,namespace) * on (pod) group_left( kubernetes_namespace )  sum by (pod)(kube_pod_status_phase{phase=~\"Running|Pending\"}))  / scalar(sum(machine_memory_bytes { node_role_kubernetes_io_compute=\"true\"})) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes { node_role_kubernetes_io_compute=\"true\"}) / (1024*1024*1024)"
    }
   ]
  }
 ]
}